# Generated by Django 6.0.6 on 2026-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_project", "0013_bornin_diedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="nobel_prizes",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="nobel_prizes",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
