# Generated by Django 6.0.6 on 2026-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_project", "0014_person_nobel_prizes_versionperson_nobel_prizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="nobel_prizes",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="nobel_prizes",
        ),
        migrations.AddField(
            model_name="person",
            name="biography",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="biography",
            field=models.TextField(blank=True, default=""),
        ),
    ]
