# Generated by Django 6.0.6 on 2026-07-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
        ("sample_project", "0015_remove_person_nobel_prizes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudiedAt",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
    ]
