# Generated by Django 6.0.6 on 2026-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_project', '0018_ismarriedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bornin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diedin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
